<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="FirstTestSuite" duration-ms="16045" started-at="2018-02-09T09:12:28Z" finished-at="2018-02-09T09:12:44Z">
    <groups>
    </groups>
    <test name="Emaktab" duration-ms="16045" started-at="2018-02-09T09:12:28Z" finished-at="2018-02-09T09:12:44Z">
      <class name="com.name.test.AddDesignationTest">
        <test-method status="PASS" signature="methodSetUp(java.lang.String)[pri:0, instance:com.name.test.AddDesignationTest@5f341870]" name="methodSetUp" is-config="true" duration-ms="6718" started-at="2018-02-09T14:42:37Z" finished-at="2018-02-09T14:42:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodSetUp -->
        <test-method status="PASS" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:com.name.test.AddDesignationTest@5f341870]" name="setUpClass" is-config="true" duration-ms="0" started-at="2018-02-09T14:42:44Z" finished-at="2018-02-09T14:42:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@20398b7c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="SKIP" signature="LoginEmaktabTest(java.util.HashMap)[pri:1, instance:com.name.test.AddDesignationTest@5f341870]" name="LoginEmaktabTest" duration-ms="0" started-at="2018-02-09T14:42:44Z" data-provider="LoginData" finished-at="2018-02-09T14:42:44Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:115)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.name.base.ExcelReader.getRowDataMap(ExcelReader.java:32)
	at com.name.test.AddDesignationTest.loginData(AddDesignationTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginEmaktabTest -->
        <test-method status="SKIP" signature="AddDesgination(java.util.HashMap)[pri:2, instance:com.name.test.AddDesignationTest@5f341870]" name="AddDesgination" duration-ms="0" started-at="2018-02-09T14:42:44Z" data-provider="AddDesgination" finished-at="2018-02-09T14:42:44Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:115)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.name.base.ExcelReader.getRowDataMap(ExcelReader.java:32)
	at com.name.test.AddDesignationTest.AddData(AddDesignationTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddDesgination -->
        <test-method status="PASS" signature="methodTearDown()[pri:0, instance:com.name.test.AddDesignationTest@5f341870]" name="methodTearDown" is-config="true" duration-ms="644" started-at="2018-02-09T14:42:44Z" finished-at="2018-02-09T14:42:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTearDown -->
      </class> <!-- com.name.test.AddDesignationTest -->
      <class name="com.name.test.EmaktabLoginTest">
        <test-method status="PASS" signature="methodSetUp(java.lang.String)[pri:0, instance:com.name.test.EmaktabLoginTest@14bf9759]" name="methodSetUp" is-config="true" duration-ms="7745" started-at="2018-02-09T14:42:28Z" finished-at="2018-02-09T14:42:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodSetUp -->
        <test-method status="PASS" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:com.name.test.EmaktabLoginTest@14bf9759]" name="setUpClass" is-config="true" duration-ms="0" started-at="2018-02-09T14:42:36Z" finished-at="2018-02-09T14:42:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@20398b7c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="SKIP" signature="LoginEmaktabTest(java.util.HashMap)[pri:0, instance:com.name.test.EmaktabLoginTest@14bf9759]" name="LoginEmaktabTest" duration-ms="0" started-at="2018-02-09T14:42:36Z" data-provider="TestData" finished-at="2018-02-09T14:42:36Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:115)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.name.base.ExcelReader.getRowDataMap(ExcelReader.java:32)
	at com.name.test.EmaktabLoginTest.loginData(EmaktabLoginTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginEmaktabTest -->
        <test-method status="PASS" signature="methodTearDown()[pri:0, instance:com.name.test.EmaktabLoginTest@14bf9759]" name="methodTearDown" is-config="true" duration-ms="891" started-at="2018-02-09T14:42:36Z" finished-at="2018-02-09T14:42:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTearDown -->
      </class> <!-- com.name.test.EmaktabLoginTest -->
    </test> <!-- Emaktab -->
  </suite> <!-- FirstTestSuite -->
</testng-results>
